version: '3.7'

networks:
  slim-net:
    name: slim
    driver: bridge

volumes:
    logs:
        driver: local

services:
    slim:
        build:
            context: .
            dockerfile: dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - slim-net
    
    postgres:
        image: postgres:13.3
        restart: always
        environment:
            POSTGRES_DB: "homestead"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "secret"
        ports:
            - "5432:5432"
        networks:
            - slim-net

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:7.2
        environment:
            PGADMIN_DEFAULT_EMAIL: "a@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "secret"
            PGADMIN_CONFIG_SERVER_MODE: "False"
        ports:
            - "5050:80"
        restart: unless-stopped
        networks:
            - slim-net
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1G